#!/bin/bash

for f in friendfund/public/js/*.js; do 
	echo "===================================Processing====================================="; 
        echo "===================================$f";
	cat $f |./friendfund/resources/jslint.js;
done

for f in friendfund/public/js/friendfund/*.js; do
        echo "===================================Processing=====================================";
        echo "===================================$f";
        cat $f |./friendfund/resources/jslint.js;
done
